
resize:
  _target_: torchvision.transforms.Resize
  size: 50
random_crop:
  _target_: torchvision.transforms.RandomCrop
  size: 50
random_perspective:
  _target_: torchvision.transforms.RandomPerspective
  distortion_scale: 0.75
  p: 1.0